package Principal;


import Principal.BaseDatos;
import java.io.FileInputStream;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import Principal.SegundaInterface;
import java.io.File;
import java.sql.SQLException;
public class INTERFACE extends javax.swing.JFrame {

    /**
     * Creates new form INTERFACE
     */
    public INTERFACE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TXT_IDENTIDAD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TXT_NOMBRE = new javax.swing.JTextField();
        APELLIDO = new javax.swing.JLabel();
        TXT_APELLIDO = new javax.swing.JTextField();
        SEXO = new javax.swing.JLabel();
        JCB_SEXO = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        JCB_DEPARTAMENTO = new javax.swing.JComboBox<>();
        JCB_MUNICIPIO = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        JB_GUARDAR = new javax.swing.JButton();
        JB_VER = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TXT_PESO = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("IDENTIDAD");

        jLabel2.setText("NOMBRE");

        APELLIDO.setText("APELLIDO");

        SEXO.setText("SEXO");

        JCB_SEXO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OTROS", "MASCULINO", "FEMENINO" }));

        jLabel3.setText("Departamento:");

        JCB_DEPARTAMENTO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " Atlántida, ", " Choluteca, ", " Colón", " Comayagua, ", " Copán,", " Cortes", " El Paraíso,", " Francisco Morazán, ", " Gracias a Dios, ", ". Intibucá, ", ". Islas de l", ". La Paz", ". Lempira,", ". Ocotepeque", ". Olancho, J", ". Santa Bárbara", ". Valle, ", ". Yoro", " " }));

        JCB_MUNICIPIO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " La Ceiba", "Choluteca", "Trujillo", "Comayagua", "Santa Rosa de Copán", "San Pedro de Sula", "Yuscarán", "Tegucigalpa", "Puerto Lempira", " La Esperanza", "Roatán", "La Paz", "Gracias", "Nuevo Ocotepeque", "Juticalpa", "Santa Bárbara", "Nacaome", "Yoro" }));

        jLabel4.setText("Municipio");

        JB_GUARDAR.setText("Guardar");
        JB_GUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_GUARDARActionPerformed(evt);
            }
        });

        JB_VER.setText("Ver");
        JB_VER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_VERActionPerformed(evt);
            }
        });

        jLabel5.setText("PESO");

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                                        .addComponent(JCB_MUNICIPIO, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(APELLIDO, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TXT_IDENTIDAD)
                                            .addComponent(TXT_NOMBRE)
                                            .addComponent(TXT_APELLIDO, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                            .addComponent(TXT_PESO))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JB_GUARDAR, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(JB_VER)
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(SEXO, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JCB_SEXO, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JCB_DEPARTAMENTO, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TXT_IDENTIDAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(TXT_NOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(APELLIDO)
                    .addComponent(TXT_APELLIDO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TXT_PESO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCB_SEXO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SEXO))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JCB_DEPARTAMENTO, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCB_MUNICIPIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JB_GUARDAR, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JB_VER))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_GUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_GUARDARActionPerformed
        PreparedStatement Sentencia;
        FileInputStream fi;
          String sql = "INSERT INTO" + " HUMANO (ID, NOMBRE, APELLIDO, PESO, SEXO, DEPARTAMENTO, MUNICIPIO)"
        +" VALUES(?,?,?,?,?,?,?)"; 
        try{
         Sentencia= BaseDatos.Conexion.prepareStatement(sql);
         Sentencia.setString(1,TXT_IDENTIDAD.getText());
         Sentencia.setString(2,TXT_NOMBRE.getText());
         Sentencia.setString(3,TXT_APELLIDO.getText());
         Sentencia.setString(4,TXT_PESO.getText());
         Sentencia.setString(5,JCB_SEXO.getSelectedItem().toString());
         Sentencia.setString(6,JCB_DEPARTAMENTO.getSelectedItem().toString());
         Sentencia.setString(7,JCB_MUNICIPIO.getSelectedItem().toString());
         Sentencia.executeUpdate();
         System.out.println(sql);       
        }catch(Exception e){
             JOptionPane.showMessageDialog(null,"error"+ e);
  
        }
          
    }//GEN-LAST:event_JB_GUARDARActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         BaseDatos.AbrirConexionDB();
    }//GEN-LAST:event_formWindowOpened

    private void JB_VERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_VERActionPerformed
       SegundaInterface From= new SegundaInterface();
        From.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_JB_VERActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  PreparedStatement Sentencia;
        FileInputStream fi;
        
        String sql = "UPDATE HUMANO "+" NOMBRE = ?,  APELLIDO = ?,PESO = ?, SEXO = ?, DEPARTAMENTO = ?, MUNICIPIO = ?"
          +"WHERE ID = ? " ;
        try{
         Sentencia= BaseDatos.Conexion.prepareStatement(sql);
         Sentencia.setString(0,TXT_IDENTIDAD.getText());
         Sentencia.setString(1,TXT_NOMBRE.getText());
         Sentencia.setString(2,TXT_APELLIDO.getText());
         Sentencia.setString(3,TXT_PESO.getText());
         Sentencia.setString(4,JCB_SEXO.getSelectedItem().toString());
         Sentencia.setString(5,JCB_DEPARTAMENTO.getSelectedItem().toString() ); 
         Sentencia.setString(6,JCB_MUNICIPIO.getSelectedItem().toString() ); 
         Sentencia.executeUpdate();
         System.out.println(sql); 
         JOptionPane.showMessageDialog(null, " La Informacion a sido MODIFICADA");
        }catch(Exception ex){
            System.out.println("error"+ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INTERFACE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INTERFACE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INTERFACE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INTERFACE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INTERFACE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel APELLIDO;
    private javax.swing.JButton JB_GUARDAR;
    private javax.swing.JButton JB_VER;
    public static javax.swing.JComboBox<String> JCB_DEPARTAMENTO;
    public static javax.swing.JComboBox<String> JCB_MUNICIPIO;
    public static javax.swing.JComboBox<String> JCB_SEXO;
    private javax.swing.JLabel SEXO;
    public static javax.swing.JTextField TXT_APELLIDO;
    public static javax.swing.JTextField TXT_IDENTIDAD;
    public static javax.swing.JTextField TXT_NOMBRE;
    public static javax.swing.JTextField TXT_PESO;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
